//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TUniversity.h"

TUniversity::TUniversity(string univName) {
    name = univName;
}

void TUniversity::printData() {
    cout << name;
}

void TUniversity::setData(string name, int age) {
    student.setName(name);
    student.setAge(age);
}

