//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zwierze.h
//  @ Date : 26.02.2018
//  @ Author : 
//
//


#if !defined(_ZWIERZE_H)
#define _ZWIERZE_H


class Zwierze {
public:
	string typ = "";
	void zrob_cos(string ssak);
};

void Zwierze::zrob_cos(string ssak){
	ssak = "Piesek";
	cout << ssak << endl;
}

#endif  //_ZWIERZE_H
