//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLibrary.cpp
//  @ Date : 05.03.2018
//  @ Author :
//
//


#include "TLibrary.h"

TLibrary::TLibrary(string libName) {
    libraryName = libName;
}

TLibrary::~TLibrary() {
    libraryName = "";
}

void TLibrary::printData() {
    cout << libraryName;
}

void TLibrary::setData(string title, string mark) {
    book->bookTitle = title;
    book->shelfMark = mark;
}

