//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.h
//  @ Date : 12.03.2018
//  @ Author :
//
//


#if !defined(_TSTUDENT_H)
#define _TSTUDENT_H
#include<iostream>
using namespace std;

class TStudent {
public:
	TStudent();
	~TSudent();
};

#endif  //_TSTUDENT_H
