//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.h
//  @ Date : 12.03.2018
//  @ Author :
//
//


#if !defined(_TUNIVERSITY_H)
#define _TUNIVERSITY_H
#include<vector>
#include<iostream>
using namespace std;

class TUniversity {
public:
	void attach();
	void detach();
private:
	vector<TStudent*> students;
	vector<TStudent*>: iterator it;
};

#endif  //_TUNIVERSITY_H
