//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TUniversity.h"

void TUniversity::attach() {
    if(students.size() <= 5){
        TStudent *st = new TStudent;
        students.push_back(st);
    }

}

void TUniversity::detach() {
    if(studets.size() > 0)
        students.pop_back(st);
}

