//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBernoulli.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "TBernoulli.h"

void TBernoulli::bernoulli(double p, int n, int k) {
    q = 1 - p;
    P = (pNewton->newton(n, k) *
    pPower->power(p, k) *
    pPower->power(q, n - k) );
    cout << P << endl;

}

TBernoulli::TBernoulli() {
    pNewton = new TNewton;
    pPower = new pPower();
}

TBernoulli::~TBernoulli() {
   delete pNewton;
   delete pPower;
}

