//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBernoulli.h
//  @ Date : 19.03.2018
//  @ Author :
//
//


#if !defined(_TBERNOULLI_H)
#define _TBERNOULLI_H


class TBernoulli {
public:
	void bernoulli(double p, int n, int k);
private:
	TPower *pPower;
	TNewton *pNewton;
	double q;
	double p;
	TBernoulli();
	~TBernoulli();
};

#endif  //_TBERNOULLI_H
