//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFactorial.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "TFactorial.h"

double TFactorial::factorial(int n) {
    if(n == 0)
        return 1;
    return n * factorial(n - 1);

}

