//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFactorial.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_TFACTORIAL_H)
#define _TFACTORIAL_H


class TFactorial {
public:
	double factorial(int n);
};

#endif  //_TFACTORIAL_H
