//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPower.cpp
//  @ Date : 19.03.2018
//  @ Author :
//
//


#include "TPower.h"

double TPower::power(double a, int b) {
    if(b == 0)
        return 1;
    return n * power(a, b - 1);
}

