//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPower.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_TPOWER_H)
#define _TPOWER_H


class TPower {
public:
	double power(double a, int b);
};

#endif  //_TPOWER_H
