//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStudent.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TStudent.h"

TStudent::TStudent() {

}

TStudent::~TStudent() {

}

void TStudent::setName(string name) {
    studetName = name;
}

string TStudent::getName() {
    return studetName;
}

void TStudent::setAge(int age) {
    studentAge = age;
}

int TStudent::getAge() {
    return studentAge;
}

