//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TUniversity.cpp
//  @ Date : 12.03.2018
//  @ Author :
//
//


#include "TUniversity.h"

void TUniversity::attach(TStudent* st) {
    st = new TStudent;
    students.push_back(st);
    i++;
}

void TUniversity::detach() {
    students.pop_back(st);
}

void TUniversity::printData(int i) {
    cout << i ;
}

void TUniversity::setData(int i, string name, int age) {
    students.back().studentsName = name;
    students.back().studentsAge = age;
    i = 0;

}

